language : php

php :
    - 7

before_script:
  - composer selfupdate
  - composer install
  - composer dump-autoload -o

script:
    - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
